# Generated by Django 3.1.12 on 2025-10-21 19:21

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=200)),
                ('horario_funcionamento', models.CharField(max_length=100)),
                ('taxa_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='parques/')),
            ],
        ),
        migrations.CreateModel(
            name='Trilhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('dificuldade', models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], max_length=30)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='trilhas/')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='myapp.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='myapp.parque')),
            ],
        ),
    ]
