# Generated by Django 4.0.10 on 2025-11-21 11:40

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_eventos_id_alter_trilhas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='parque',
        ),
        migrations.RemoveField(
            model_name='trilhas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trilhas',
            name='parque',
        ),
        migrations.AddField(
            model_name='eventos',
            name='parque_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trilhas',
            name='parque_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parque',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='myapp.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Novidades',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novidades', to='myapp.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='myapp.parque')),
            ],
        ),
    ]
