# Generated by Django 4.0.10 on 2025-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_eventos_id_remove_eventos_parque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parque',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='temporada',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trilhas',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parque',
            name='localizacao',
            field=models.TextField(max_length=200),
        ),
    ]
