# Generated by Django 4.0.10 on 2025-11-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_eventos_ativo_parque_ativo_temporada_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidade',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='parque_id',
        ),
        migrations.RemoveField(
            model_name='novidades',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='temporada',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='trilhas',
            name='parque_id',
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='parque',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='myapp.parque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novidades',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parque',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporada',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trilhas',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trilhas',
            name='parque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.parque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parque'),
        ),
        migrations.AlterField(
            model_name='novidades',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parque'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parque'),
        ),
    ]
