# Generated by Django 4.0.10 on 2025-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_disponibilidade__id_remove_eventos_parque_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='parque',
        ),
        migrations.AddField(
            model_name='parque',
            name='dia_semana',
            field=models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trilhas',
            name='data_fim',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trilhas',
            name='data_inicio',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trilhas',
            name='distancia',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Disponibilidade',
        ),
        migrations.DeleteModel(
            name='Temporada',
        ),
    ]
